apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: kubia
  spec:
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    minReadySeconds: 10
    template:
      metadata:
        labels:
          app: kubia
          version: v2
      spec:
        containers:
        - name: kubia
          image: luksa/kubia:v2
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "64M"
              cpu: "100m"
            limits:
              memory: "128M"
              cpu: "100m"