apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: kubia-v1
  spec:
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    minReadySeconds: 10
    template:
      metadata:
        labels:
          app: kubia
          version: v1
      spec:
        containers:
        - name: kubia
          image: luksa/kubia:v1
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "64M"
              cpu: "100m"
            limits:
              memory: "128M"
              cpu: "100m"

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: kubia-v2
  spec:
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    minReadySeconds: 10
    template:
      metadata:
        labels:
          app: kubia
          version: v2
      spec:
        containers:
        - name: kubia
          image: luksa/kubia:v2
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "64M"
              cpu: "100m"
            limits:
              memory: "128M"
              cpu: "100m"

- apiVersion: v1
  kind: Service
  metadata:
    name: kubia
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: kubia
    sessionAffinity: None

- apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: kubia
  spec:
    host: kubia
    subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2

- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: kubia
  spec:
    selector:
      istio: ingressgateway
    servers:
      - port:
          number: 80
          name: http
          protocol: HTTP
        hosts:
          - "kubia.com"

- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: kubia
  spec:
    hosts:
      - "kubia.com"
    gateways:
      - kubia
    http:
      - match:
          - headers:
              role:
                exact: "admin"
        route:
          - destination:
              host: kubia
              subset: v2
        timeout: 5s
      - route:
          - destination:
              host: kubia
              subset: v1
        timeout: 5s

